# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [14]:
# Write your code below.
%load_ext dotenv
%dotenv

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [ ]:
import dask.dataframe as dd
import pandas as pd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [16]:
import os
from glob import glob

# Write your code below.
PRICE_DATA = os.getenv("PRICE_DATA")

parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive=True)
parquet_files

['../../05_src/data/prices/DTF/DTF_2002/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2002/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2005/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2005/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2004/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2004/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2003/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2003/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1997/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1997/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1999/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1999/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1998/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1998/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1996/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1996/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1991/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1991/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2010/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2010/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2017/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2017/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2019/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2019/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2018/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2018/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2020/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2020/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2016/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2016/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2011/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2011/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2008/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2008/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2006/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2006/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2001/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2001/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2000/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2000/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2007/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2007/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2009/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2009/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1994/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1994/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1993/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1993/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1992/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1992/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_1995/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_1995/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2014/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2014/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2013/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2013/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2012/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2012/part.1.parquet',
 '../../05_src/data/prices/DTF/DTF_2015/part.0.parquet',
 '../../05_src/data/prices/DTF/DTF_2015/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1992/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1992/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1995/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1995/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1994/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1994/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1993/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1993/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2009/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2009/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2000/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2000/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2007/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2007/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2006/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2006/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2001/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2001/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2008/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2008/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2012/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2012/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2015/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2015/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2014/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2014/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2013/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2013/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1996/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1996/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1998/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1998/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1999/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1999/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1997/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_1997/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2004/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2004/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2003/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2003/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2002/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2002/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2005/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2005/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2016/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2016/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2011/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2011/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2018/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2018/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2020/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2020/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2019/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2019/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2010/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2010/part.1.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2017/part.0.parquet',
 '../../05_src/data/prices/ICUI/ICUI_2017/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2012/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2012/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2015/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2015/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2014/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2014/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2013/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2013/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1980/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1980/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1987/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1987/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1989/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1989/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1988/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1988/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1986/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1986/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1981/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1981/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1992/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1992/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1995/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1995/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1994/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1994/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1993/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1993/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2000/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2000/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2007/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2007/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2009/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2009/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2008/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2008/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2006/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2006/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2001/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2001/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2018/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2018/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2020/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2020/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2016/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2016/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2011/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2011/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2010/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2010/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2017/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2017/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2019/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2019/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1984/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1984/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1983/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1983/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1982/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1982/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1985/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1985/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1998/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1998/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1996/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1996/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1991/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1991/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1990/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1990/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1997/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1997/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1999/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_1999/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2004/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2004/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2003/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2003/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2002/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2002/part.1.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2005/part.0.parquet',
 '../../05_src/data/prices/BKTI/BKTI_2005/part.1.parquet',
 '../../05_src/data/prices/APTX/APTX_2018/part.0.parquet',
 '../../05_src/data/prices/APTX/APTX_2018/part.1.parquet',
 '../../05_src/data/prices/APTX/APTX_2020/part.0.parquet',
 '../../05_src/data/prices/APTX/APTX_2020/part.1.parquet',
 '../../05_src/data/prices/APTX/APTX_2019/part.0.parquet',
 '../../05_src/data/prices/APTX/APTX_2019/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2008/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2008/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2001/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2001/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2006/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2006/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2007/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2007/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2000/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2000/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2009/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2009/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2013/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2013/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2014/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2014/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2015/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2015/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2012/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2012/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_1997/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_1997/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_1999/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_1999/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_1998/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_1998/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_1996/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_1996/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2005/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2005/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2002/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2002/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2003/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2003/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2004/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2004/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2017/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2017/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2010/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2010/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2019/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2019/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2020/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2020/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2018/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2018/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2011/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2011/part.1.parquet',
 '../../05_src/data/prices/ANF/ANF_2016/part.0.parquet',
 '../../05_src/data/prices/ANF/ANF_2016/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2020/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2020/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2018/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2018/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2011/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2011/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2016/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2016/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2017/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2017/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2010/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2010/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2019/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2019/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2015/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2015/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2012/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2012/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2013/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2013/part.1.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2014/part.0.parquet',
 '../../05_src/data/prices/AOSL/AOSL_2014/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2010/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2010/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2017/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2017/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2019/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2019/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2018/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2018/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2020/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2020/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2016/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2016/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2011/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2011/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2002/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2002/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2005/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2005/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2004/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2004/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2003/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2003/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_1999/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_1999/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2014/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2014/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2013/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2013/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2012/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2012/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2015/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2015/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2008/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2008/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2006/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2006/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2001/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2001/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2000/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2000/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2007/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2007/part.1.parquet',
 '../../05_src/data/prices/INFY/INFY_2009/part.0.parquet',
 '../../05_src/data/prices/INFY/INFY_2009/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2004/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2004/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2003/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2003/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2005/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2005/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2018/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2018/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2020/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2020/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2016/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2016/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2011/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2011/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2010/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2010/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2017/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2017/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2019/part.0.parquet',
 '../../05_src/data/prices/UVE/UVE_2019/part.1.parquet',
 '../../05_src/data/prices/UVE/UVE_2007/part.0.parquet',

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [ ]:
# Write your code below.
dd_px = dd.read_parquet(parquet_files).set_index("ticker")

dd_feat = (
    dd_px
        .groupby('ticker', group_keys=False)
        .apply(
            lambda x: x.sort_values('Date', ascending = True) # sort by date before applying shift
                       .assign(Close_lag_1 = x['Close'].shift(1),
                               Adj_Close_lag_1 = x['Adj Close'].shift(1)
                               ), 
            meta = pd.DataFrame(data ={'Date': 'datetime64[ns]',
                    'Open': 'f8',
                    'High': 'f8',
                    'Low': 'f8',
                    'Close': 'f8',
                    'Adj Close': 'f8',
                    'Volume': 'i8',
                    'source': 'object',
                    'Year': 'int32',
                    'Close_lag_1': 'f8',
                    'Adj_Close_lag_1': 'f8'},
                    index = pd.Index([], dtype=pd.StringDtype(), name='ticker'))
    ).assign(
    returns = lambda x: x['Close']/x['Close_lag_1'] - 1,
    hi_lo_range = lambda x: x['High'] - x['Low']
))

dd_feat.head()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Adj_Close_lag_1,returns,hi_lo_range
ticker,,,,,,,,,,,,,
A,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A.csv,1999,NaN,NaN,NaN,7.153078
A,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A.csv,1999,46.490002,45.150257,-0.378779,2.280043
A,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A.csv,1999,47.099998,45.742683,-0.331772,2.816525
A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A.csv,1999,46.540001,45.198818,-0.385211,2.592991
A,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A.csv,1999,47.990002,46.607040,-0.387949,1.385908

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [18]:
# Write your code below.
dd_feat = dd_feat.compute() # Convert to pandas dataframe (reminder: ticker is still the index)

# Add new feature with moving average of 'returns' using 10-day window
dd_feat['returns_ma_10'] = (
    dd_feat["returns"]
        .groupby(level=0)
        .rolling(10).mean()
        .reset_index(level=0, drop=True)
)

dd_feat.head(15)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Adj_Close_lag_1,returns,hi_lo_range,returns_ma_10
ticker,,,,,,,,,,,,,,
A,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A.csv,1999,NaN,NaN,NaN,7.153078,NaN
A,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A.csv,1999,31.473534,27.068665,-0.082386,2.280043,NaN
A,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A.csv,1999,28.880543,24.838577,0.089783,2.816525,NaN
A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A.csv,1999,31.473534,27.068665,-0.090909,2.592991,NaN
A,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A.csv,1999,28.612303,24.607880,0.026563,1.385908,NaN
A,1999-11-26,29.238197,29.685265,29.148785,29.461731,25.338428,1729400.0,A.csv,1999,29.372318,25.261524,0.003044,0.536480,NaN
A,1999-11-29,29.327610,30.355865,29.014664,30.132332,25.915169,4074700.0,A.csv,1999,29.461731,25.338428,0.022762,1.341202,NaN
A,1999-11-30,30.042919,30.713520,29.282904,30.177038,25.953619,4310000.0,A.csv,1999,30.132332,25.915169,0.001484,1.430616,NaN
A,1999-12-01,30.177038,31.071173,29.953505,30.713520,26.415012,2957300.0,A.csv,1999,30.177038,25.953619,0.017778,1.117668,NaN
A,1999-12-02,31.294706,32.188843,30.892345,31.562946,27.145563,3069800.0,A.csv,1999,30.713520,26.415012,0.027656,1.296497,NaN
A,1999-12-03,32.144135,32.680614,31.697067,31.831188,27.376266,3041600.0,A.csv,1999,31.562946,27.145563,0.008499,0.983547,0.002427
A,1999-12-06,32.367668,33.217094,32.322960,32.725323,28.145258,2250700.0,A.csv,1999,31.831188,27.376266,0.028090,0.894135,0.013475
A,1999-12-07,32.725323,32.904148,31.697067,32.367668,27.837664,2215900.0,A.csv,1999,32.725323,28.145258,-0.010929,1.207081,0.003404
A,1999-12-08,32.367668,32.635910,32.054722,32.322960,27.799208,1887800.0,A.csv,1999,32.367668,27.837664,-0.001381,0.581188,0.012356
A,1999-12-09,32.367668,32.859444,32.367668,32.770027,28.183710,2029000.0,A.csv,1999,32.322960,27.799208,0.013831,0.491776,0.011083

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?
+ Would it have been better to do it in Dask? Why?

(1 pt)

Answer: It was not necessary to convert the Dask dataframe to pandas because Dask can also calculate moving average returns. It would not have been better to do it in Dask since the dataset is small enough to fit in memory, and pandas can be faster locally for a dataset this size.

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.